name: Windows build for Zed

on:
  push:
    tags:
      - "daily-release-[0-9]+"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  zed:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Enable long paths in Windows
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" `
            -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
        shell: powershell

      - name: Clone zed
        run: git clone https://github.com/zed-industries/zed.git

      - name: Configure Git for long paths
        run: |
          git config --system core.longpaths true
        shell: powershell

      - name: Build Zed
        run: |
          cd zed
          cargo build --release

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./zed/target/release/zed.exe
          tag: ${{ github.ref_name }}
          overwrite: true
          make_latest: false  # Add this to avoid issues with "latest" release
